notifications:
  webhooks:
    - https://webhook.commit-email.info/
dist: xenial
services:
  - docker
apt:
  packages:
    - mysql-client
matrix:
  include:
    - name: "MySQL 5.7"
      script:
        - test/build.sh mysql57
    - name: "MySQL 8.0"
      script:
        - test/build.sh mysql80
